### ISSUE TITLE
It's still possible to open multiple windows…

### ISSUE THREAD

**Issue by gre0j** [elementary/shortcut-overlay#52]
…when screenshot-tool is open/present on screen. #31 #18

![bildschirmfoto von 2018-09-29 00-39-57](https://user-images.githubusercontent.com/23266409/46236737-7589de80-c380-11e8-8bfa-ce1ddcc07553.png)
![screenshot von 2018-09-29 00 40 45](https://user-images.githubusercontent.com/23266409/46236743-7d498300-c380-11e8-9a20-7093ce7d8d12.png)

**Comment by ryonakano** [comment]
It seems that displaying an app window always on top causes this issue. I can confirm this issue with Calcurator in that way:

![2018-10-14 18 08 34](https://user-images.githubusercontent.com/26003928/46914730-44deb180-cfdc-11e8-9490-c440e54c1b0c.png)

**Comment by cassidyjames** [comment]
I think there's a caveat that the always-on-top window has to overlap with where the overlay is trying to go.

**Comment by cassidyjames** [comment]
This seems to be caused by https://github.com/elementary/shortcut-overlay/commit/f2e9cdd1d6073cc0265b3c8e574cbea65163308c

reverting this line specifically seems to fix it, but I'm not 100% sure if it was needed for any other fix:

https://github.com/elementary/shortcut-overlay/commit/f2e9cdd1d6073cc0265b3c8e574cbea65163308c#diff-66d904d87bb1ee73704e5f5ea4be6bcdR28
